config/routes.rb
Rails.application.routes.draw do

  resources :candidates_lists, path: "kandidatni-listiny", only: [:new, :create, :index, :show, :edit, :update] do
    collection do
      post :preview
    end
  end
  get '/candidates_lists/:candidates_list_id/declaration/:id', to: 'candidates_lists#declaration', as: 'declaration'
  get '/candidates_lists/:id/declarations', to: 'candidates_lists#declarations', as: 'declarations'

  namespace :backoffice do
    resources :attendance_lists, only: [:new, :create, :show] do
      member do
        get :guests
      end
    end
    resources :events, only: [:index, :show]
    resources :stats, only: [:index] do
      collection do
        get 'changes'
      end
    end
    resources :people do
      collection do
        get 'addresses'
      end
      member do
        post 'member_paid'
        post 'supporter_paid'
      end
      collection do
        get :autocomplete_person_id
        get :autocomplete_person_email
        get :autocomplete_person_name
        get :autocomplete_person_phone
        get :with_unknown_address
        get :with_bad_region
        get :without_signed_application
        get :members_without_signed_application
        get :new_registrations
        get :membership_requests
      end
    end
  end

  resources :profiles do
    collection do
      get 'personal'
      get 'photos'
      get 'credentials'
      get 'addresses'
      get 'contacts'
      get 'guesting'
      get 'membership'
    end
  end

  get '/registrations/member', to: 'registrations#member'
  get '/registrations/supporter', to: 'registrations#supporter'

  patch '/profiles', to: 'profiles#update'
  use_doorkeeper

  resources :profile_pictures
  resources :contacts
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :signed_applications
  resources :profile_photos

  get '/auth/token'
  get '/auth/public_key'
  get '/auth/profile'
  get '/auth/me'

  devise_for :people, :controllers => { :omniauth_callbacks => "people/omniauth_callbacks" }

  resources :webdav_passwords
  resources :bodies
  resources :roles, only: [:index, :destroy, :new, :create] do
    get :autocomplete_person_last_name, :on => :collection
  end

  resources :branches do
    resources :people
    resources :contacts, only: :index
    member do
      get 'coordinator'
      get 'map'
      get 'awaiting_domestic_people'
      get 'domestic_members'
      get 'domestic_supporters'
      get 'guest_people'
      get 'unpaid_domestic_members'
    end
  end
  resources :organizations
  resources :people do
    resources :contacts
    resources :notes, only: [:new, :create]

    member do
      get 'application'
      get 'signed_application'
      get 'private'
      get 'photo'
      get 'cv'
      post 'approve'
      post 'reject'
      post 'cancel_membership'
      get 'cancel_membership_request'
    end
    collection do
      get 'profile'
      get 'dashboard'
      get 'beran_export'
    end
  end

  resources :supporter_memberships, only: [:new, :create]

  resources :regions do
    resources :people
    resources :branches, only: :index
    resources :councilors, only: :index
    resources :contacts, only: :index
    resource :body, only: :show
    member do
      get 'domestic_members'
      get 'domestic_supporters'
      get 'guest_people'
      get 'mestske_casti'
      get 'okresy'
      get 'map'
      get 'awaiting_domestic_people'
      get 'unpaid_domestic_members'
    end
  end

  resources :regions, path: "kraje"
  resources :councilors, path: "zastupitele"
  resources :councilors, only: :index

  post "/people/:id/supporter_payments", to: "finance_api#supporter_payments"
  post "/people/:id/member_payments", to: "finance_api#member_payments"
  get "/people/:id/payments", to: "finance_api#payments"
  post "/people/:id/supporter_paid", to: "finance_api#supporter_paid"
  post "/people/:id/member_paid", to: "finance_api#member_paid"

  root 'people#dashboard'
end

app/models/branch.rb
# Třída Branch reprezentuje místní Pobočku.
class Branch < Organization

  # patří do kraje
  belongs_to :region, :foreign_key => "parent_id"

  # má svého koordinátora
  has_one :coordinator, -> { where("since < ? and till > ?", Time.now, Time.now ) }

  # má seznam i bývalých koordinátorů
  has_many :coordinators, -> { where("till < ?", Time.now) }

  # má svého náboráře
  has_one :recruiter, -> { where("since < ? and till > ?", Time.now, Time.now ) }

  # má kmenové členy a příznivce
  has_many :domestic_people, class_name: "Person", foreign_key: "domestic_branch_id"
  has_many :domestic_members, -> { where('status="regular_member"') },class_name: "Person", foreign_key: "domestic_branch_id"
  has_many :domestic_supporters, -> { where(status: "regular_supporter") },class_name: "Person", foreign_key: "domestic_branch_id"

  has_many :awaiting_domestic_people, -> { includes(:membership_request).where.not("membership_requests.membership_requested_on" => nil) }, class_name: "Person", foreign_key: "domestic_branch_id"
  # má hostující členy a příznivce
  has_many :guest_people, class_name: "Person", foreign_key: "guest_branch_id"

  # validace na unikatni jmeno pobocky
  validates :name, uniqueness: true

  # má kmenové a hostující členy a příznivce
  def people
  	domestic_people+guest_people
  end

end

app/controllers/branches_controller.rb
# -*- encoding : utf-8 -*-
class BranchesController < ApplicationController
  before_action :set_branch, only: [:show, :update, :destroy, :coordinator, :awaiting_domestic_people, :domestic_members, :domestic_supporters, :guest_people, :unpaid_domestic_members, :map]

  before_action :authenticate_person!, except: :show

  # GET /branches.json
  def index
    if params[:region_id]
      @region = Region.find(params[:region_id])
      @branches = @region.branches
    else
      @branches = Branch.all
    end
    @branches = @branches.order(:name)
    respond_to do |format|
      format.html
      format.json {render json: @branches}
    end
  end

  def map
    render 'people/map'
  end

  # GET /branches/1.json
  def show
    respond_to do |format|
      format.html
      format.json
    end
  end

  # GET /roles/new
  def new
    authorize!(:create, Branch)
    @branch = Branch.new
  end

  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)
    authorize!(:create, @branch)
    respond_to do |format|
      if @branch.save
        @branch.events.create(default_event_params.merge({
          command: "CreateBranch",
          name: "BranchCreated",
          changes: @branch.previous_changes
        }))
        format.html { redirect_to @branch, notice: 'Pobočka byla úspěšně založena.' }
        format.json { render json: @branch, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1.json
  def update
    authorize!(:update, @branch)
    respond_to do |format|
      if @branch.update(branch_params)
        format.json { head :no_content }
      else
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1.json
  def destroy
    authorize!(:destroy, @branch)
    @branch.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:name, :parent_id)
    end

end

app/views/branches/_branch.html.erb
<div>Název: <%= link_to branch.name, branch %></div>
<% if branch.coordinator.try(:person) %>
<div>Kooridnátor: <%= link_to branch.coordinator.person.name %></div>
<div>Telefon: <%= tel_to branch.coordinator.person.phone %></div>
<div>Email: <%= mail_to branch.coordinator.person.email %></div>
<% end %>

app/views/branches/_form.html.erb
<%= simple_form_for @branch do |f| %>
<%= f.association :region %>
<%= f.input :name, label: "Název pobočky" %>
<%= f.button :submit, "Uložit" %>
<% end %>

app/views/branches/_people.html.erb
<table class="table table-striped">
  <thead><tr><th>Jméno</th><th>Email</th><th>Telefon</th><th>Městská část</th></tr></thead>
  <tbody><%=render @branch.domestic_members.accessible_by(current_ability) %></tbody>
</table>

app/views/branches/_sidebar.html.erb
<% content_for 'sidebar' do %>
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand"><%=@branch.name%></li>
    <li><%= link_to_unless_current "Koordinátor", branch_path(@branch) %></li>
    <li><%= link_to_unless_current "Sdílené kontakty", branch_contacts_path(@branch) %></li>
    <% if can? :supervise, @branch  %>
    <hr>
    <li><%= glyph_link_to 'lock', "Členové", domestic_members_branch_path(@branch) %></li>
    <li><%= glyph_link_to 'lock', "Příznivci", domestic_supporters_branch_path(@branch) %></li>
    <li><%= glyph_link_to 'lock', "Hostující", guest_people_branch_path(@branch) %></li>
    <li><%= glyph_link_to 'lock', "Zájemci o členství", awaiting_domestic_people_branch_path(@branch) %></li>
    <li><%= glyph_link_to 'lock', "Neprodloužení členové", unpaid_domestic_members_branch_path(@branch) %></li>
    <li><%= glyph_link_to 'lock', "Mapa", map_branch_path(@branch) %></li>
    <li><%= glyph_link_to 'lock', "Export", branch_people_path(@branch, format: :xls) %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/branches/awaiting_domestic_people.html.erb
<%
  page_title "Zájemci o členství"
  breadcrumb(:branch, @branch)
  render "sidebar"
%>

<table id="awaiting_domestic_people" class="table table-striped">
  <thead>
    <tr><th>Jméno</th><th>Stav</th><th>Poslední změna</th><th>Telefon</th><th>Email</th><th></th></tr>
  </thead>
  <tbody>
  <% @branch.awaiting_domestic_people.accessible_by(current_ability).reverse.each do |member| %>
    <tr>
      <td data-order="<%=member.last_name%>"><%= member.name %></td>
      <td><%= render partial:"people/membership_request_status", locals: {membership_request: member.membership_request}%></td>
      <td data-order="<%=member.membership_request.last_changed_on%>"><%=l member.membership_request.last_changed_on%></td>
      <td><%= tel_to member.phone %></td>
      <td><%= mail_to member.email %></td>
      <td><%=link_to_member_application(member)%></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= datatable :awaiting_domestic_people %>

app/views/branches/domestic_members.html.erb
<%
  page_title "Kmenoví členové"
  breadcrumb(:branch, @branch)
  render "sidebar"
%>

<table id="domestic_members" class="table table-striped">
  <thead><tr><th>Foto</th><th>Jméno</th><th>Email</th><th>Telefon</th><th>Městská část</th></tr></thead>
  <tbody><%=render @branch.domestic_members.accessible_by(current_ability) %></tbody>
</table>

<%= datatable :domestic_members %>

app/views/branches/domestic_supporters.html.erb
<%
  page_title "Kmenoví příznivci"
  breadcrumb(:branch, @branch)
  render "sidebar"
%>

<table id="domestic_supporters" class="table table-striped">
  <thead><tr><th>Foto</th><th>Jméno</th><th>Email</th><th>Telefon</th><th>Městská část</th></tr></thead>
  <tbody><%=render @branch.domestic_supporters.accessible_by(current_ability) %></tbody>
</table>

<%= datatable :domestic_supporters %>

app/views/branches/guest_people.html.erb
<%
  page_title "Hostující"
  breadcrumb(:branch, @branch)
  render "sidebar"
%>

<table id="guest_people" class="table table-striped">
  <thead><tr><th>Foto</th><th>Jméno</th><th>Email</th><th>Telefon</th><th>Městská část</th></tr></thead>
  <tbody><%=render @branch.guest_people.accessible_by(current_ability) %></tbody>
</table>

<%= datatable :guest_people %>

app/views/branches/index.html.erb
<%
	page_title 'Pobočky'
	if @region
    breadcrumb(:region_branches, @region)
	  render 'regions/sidebar'
	else
	  render 'backoffice/sidebar'
	end
%>

<table id="branches" class="table table-striped">
<thead><tr><th>Název pobočky</th><th></th><th>Koordinátor</th><th>Telefon</th><th>Email</th><th>Kmenoví členové</th></thead>
<tbody>
<% @branches.each do |branch| %>
<tr>
<td><%= link_to branch.name, branch %></td>
<td>
	<%= fa_link_to('globe', branch.homepage_url) unless branch.homepage_url.blank? %>
	<%= fa_link_to('facebook', branch.fb_page_url) unless branch.fb_page_url.blank? %>
</td>
<td><%= link_to(branch.coordinator.try(:person).try(:name), branch.coordinator.try(:person)) if branch.coordinator %></td>
<td><%= tel_to branch.coordinator.try(:person).try(:phone) %></td>
<td><%= mail_to branch.coordinator.try(:person).try(:email) %></td>
<td><%= branch.domestic_members.count %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/branches/new.html.erb
<%
  page_title 'Nová pobočka'
  render 'backoffice/sidebar'
%>
<p>Po zřízení pobočky je ještě nutné nechat zaprogramovat územní působnost, jinak nebudou do pobočky zařazování členi ani příznivci.</p>

<%= render 'form' %>

app/views/branches/show.html.erb
<%
  page_title "Pobočka #{@branch.name}"
  breadcrumb :branch, @branch
  render 'sidebar'
%>

<% if @branch.coordinator %>
<h2>Koordinátor</h2>
<%= render partial: "bodies/person", object: @branch.coordinator.person %>
<% end %>

<p>Web: <%= link_to(@branch.homepage_url, @branch.homepage_url) if @branch.homepage_url %></p>

app/views/branches/unpaid_domestic_members.html.erb
<%
  page_title "Neprodloužení členové"
  breadcrumb(:branch, @branch)
  render "sidebar"
%>

<table id="unpaid_domestic_members" class="table table-striped">
  <thead>
	<tr><th>Jméno</th><th>Stav</th><th>Telefon</th><th>Email</th><th>Zaplaceno do</th></tr>
  </thead>
  <tbody>
  <% @branch.domestic_members.not_renewed.accessible_by(current_ability).reverse.each do |member| %>
    <tr>
      <td><%= member.name %></td>
      <td><%= t member.status, scope: :person_status %></td>
      <td><%= tel_to member.phone %></td>
      <td><%= mail_to member.email %></td>
      <td><%= member.paid_till %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= datatable :unpaid_domestic_members %>