config/routes.rb
Rails.application.routes.draw do

  resources :candidates_lists, path: "kandidatni-listiny", only: [:new, :create, :index, :show, :edit, :update] do
    collection do
      post :preview
    end
  end
  get '/candidates_lists/:candidates_list_id/declaration/:id', to: 'candidates_lists#declaration', as: 'declaration'
  get '/candidates_lists/:id/declarations', to: 'candidates_lists#declarations', as: 'declarations'

  namespace :backoffice do
    resources :attendance_lists, only: [:new, :create, :show] do
      member do
        get :guests
      end
    end
    resources :events, only: [:index, :show]
    resources :stats, only: [:index] do
      collection do
        get 'changes'
      end
    end
    resources :people do
      collection do
        get 'addresses'
      end
      member do
        post 'member_paid'
        post 'supporter_paid'
      end
      collection do
        get :autocomplete_person_id
        get :autocomplete_person_email
        get :autocomplete_person_name
        get :autocomplete_person_phone
        get :with_unknown_address
        get :with_bad_region
        get :without_signed_application
        get :members_without_signed_application
        get :new_registrations
        get :membership_requests
      end
    end
  end

  resources :profiles do
    collection do
      get 'personal'
      get 'photos'
      get 'credentials'
      get 'addresses'
      get 'contacts'
      get 'guesting'
      get 'membership'
    end
  end

  get '/registrations/member', to: 'registrations#member'
  get '/registrations/supporter', to: 'registrations#supporter'

  patch '/profiles', to: 'profiles#update'
  use_doorkeeper

  resources :profile_pictures
  resources :contacts
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :signed_applications
  resources :profile_photos

  get '/auth/token'
  get '/auth/public_key'
  get '/auth/profile'
  get '/auth/me'

  devise_for :people, :controllers => { :omniauth_callbacks => "people/omniauth_callbacks" }

  resources :webdav_passwords
  resources :bodies
  resources :roles, only: [:index, :destroy, :new, :create] do
    get :autocomplete_person_last_name, :on => :collection
  end

  resources :branches do
    resources :people
    resources :contacts, only: :index
    member do
      get 'coordinator'
      get 'map'
      get 'awaiting_domestic_people'
      get 'domestic_members'
      get 'domestic_supporters'
      get 'guest_people'
      get 'unpaid_domestic_members'
    end
  end
  resources :organizations
  resources :people do
    resources :contacts
    resources :notes, only: [:new, :create]

    member do
      get 'application'
      get 'signed_application'
      get 'private'
      get 'photo'
      get 'cv'
      post 'approve'
      post 'reject'
      post 'cancel_membership'
      get 'cancel_membership_request'
    end
    collection do
      get 'profile'
      get 'dashboard'
      get 'beran_export'
    end
  end

  resources :supporter_memberships, only: [:new, :create]

  resources :regions do
    resources :people
    resources :branches, only: :index
    resources :councilors, only: :index
    resources :contacts, only: :index
    resource :body, only: :show
    member do
      get 'domestic_members'
      get 'domestic_supporters'
      get 'guest_people'
      get 'mestske_casti'
      get 'okresy'
      get 'map'
      get 'awaiting_domestic_people'
      get 'unpaid_domestic_members'
    end
  end

  resources :regions, path: "kraje"
  resources :councilors, path: "zastupitele"
  resources :councilors, only: :index

  post "/people/:id/supporter_payments", to: "finance_api#supporter_payments"
  post "/people/:id/member_payments", to: "finance_api#member_payments"
  get "/people/:id/payments", to: "finance_api#payments"
  post "/people/:id/supporter_paid", to: "finance_api#supporter_paid"
  post "/people/:id/member_paid", to: "finance_api#member_paid"

  root 'people#dashboard'
end

app/models/body.rb
# Třída reprezentuje orgán strany (ReP, Rev, KrP, RK, KK, VK)
class Body < ActiveRecord::Base
  belongs_to :organization

  # Členové jsou v orgánech v rolích/funkcích (předseda, místopředseda, koordinátor, člen)

  # v roli jsou jen během funkčního období
  has_many :roles, -> { where("since < ? and till > ?", Time.now, Time.now	) }
  has_many :people, through: :roles

  # seznam bývalých funkcionářů
  has_many :historic_roles, -> { where("till < ?", Time.now) }, source: :role, class_name: Role
  has_many :historic_people, through: :historic_roles, source: :person

  # Stávající předseda orgánu (u předsednictev)
  has_one :president, -> { where("since < ? and till > ?", Time.now, Time.now  ) }, class_name: President

  # Stávající místopředsedové orgánu (u předsednictev)
  has_many :vicepresidents, -> { where("since < ? and till > ?", Time.now, Time.now  ) }, class_name: Vicepresident

  scope :order_for_display, -> { order(display_position: :asc) }

  # Stávající členové orgánu (u komisí)
  def members
  	people.where("type='Member'")
  end

  def presidium_emails
    emails = vicepresidents.collect{|vp| vp.person.email}
    emails << president.try(:person).try(:email)
    emails
  end
end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController

  before_action :authenticate_person!, except: :index

  # GET /bodies.json
  def index
    @bodies = Body.includes(:people, :organization, :roles).all
  end

  # GET /bodies/1.json
  def show
    if params[:region_id]
      @region = Region.find(params[:region_id])
      @body = @region.presidium
    else
      @body = Body.find(params[:id])
    end
    respond_to do |format|
      format.html
      format.json { render json: @body }
    end
  end
end

app/views/bodies/_person.html.erb
<div class="col-xs-4 card">
	<div class="row">
		<div class="col-xs-4">
			<img src="<%= person.try(:photo_url) || person.person.try(:photo_url) %>"/>
		</div>
		<div class="col-xs-8">
			<h3><%= link_to person.name, person_path(person.try(:person) || person) %></h3>
			<% if person.try(:department) %>
			<strong>Resorty: <%= person.department %></strong>
			<% end %>
			<%=draw_contacts(person.contacts.accessible_by(current_ability))%>
		</div>
	</div>
</div>

app/views/bodies/_sidebar.html.erb
<% content_for 'sidebar' do %>
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">Republikové orgány</li>
    <% for body in @country.bodies %>
    <li><%= link_to_unless_current body.name.split("(").first, body %></a></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/bodies/show.html.erb
<%
  page_title @body.name
  if @region
    breadcrumb :region_presidium, @region
    render 'regions/sidebar'
  else
    breadcrumb :body, @body
    render 'sidebar'
  end
%>

<%= link_to_member_documents(@body) unless @body.acronym=="KrP" unless @region %>

<% if @body.president %>
<h2>Předseda</h2>
<div class="row">
	<%= render partial: "person", object: @body.president %>
</div>
<% end %>


<% unless @body.try(:vicepresidents).empty? %>
<% if @body.vicepresidents.size == 1 %>
<h2>Místopředseda</h2>
<% else %>
<h2>Místopředsedové</h2>
<% end %>
<div class="row">
<%= render partial: "person", collection: @body.vicepresidents.sort{|a,b| a.person.last_name<=>b.person.last_name} %>
</div>
<% end %>

<% unless @body.try(:members).empty? %>
<h2>Členové</h2>
<div class="row">
<%= render partial: "person", collection: @body.members.order(:last_name) %>
</div>
<% end %>