config/routes.rb
Rails.application.routes.draw do

  resources :candidates_lists, path: "kandidatni-listiny", only: [:new, :create, :index, :show, :edit, :update] do
    collection do
      post :preview
    end
  end
  get '/candidates_lists/:candidates_list_id/declaration/:id', to: 'candidates_lists#declaration', as: 'declaration'
  get '/candidates_lists/:id/declarations', to: 'candidates_lists#declarations', as: 'declarations'

  namespace :backoffice do
    resources :attendance_lists, only: [:new, :create, :show] do
      member do
        get :guests
      end
    end
    resources :events, only: [:index, :show]
    resources :stats, only: [:index] do
      collection do
        get 'changes'
      end
    end
    resources :people do
      collection do
        get 'addresses'
      end
      member do
        post 'member_paid'
        post 'supporter_paid'
      end
      collection do
        get :autocomplete_person_id
        get :autocomplete_person_email
        get :autocomplete_person_name
        get :autocomplete_person_phone
        get :with_unknown_address
        get :with_bad_region
        get :without_signed_application
        get :members_without_signed_application
        get :new_registrations
        get :membership_requests
      end
    end
  end

  resources :profiles do
    collection do
      get 'personal'
      get 'photos'
      get 'credentials'
      get 'addresses'
      get 'contacts'
      get 'guesting'
      get 'membership'
    end
  end

  get '/registrations/member', to: 'registrations#member'
  get '/registrations/supporter', to: 'registrations#supporter'

  patch '/profiles', to: 'profiles#update'
  use_doorkeeper

  resources :profile_pictures
  resources :contacts
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :signed_applications
  resources :profile_photos

  get '/auth/token'
  get '/auth/public_key'
  get '/auth/profile'
  get '/auth/me'

  devise_for :people, :controllers => { :omniauth_callbacks => "people/omniauth_callbacks" }

  resources :webdav_passwords
  resources :bodies
  resources :roles, only: [:index, :destroy, :new, :create] do
    get :autocomplete_person_last_name, :on => :collection
  end

  resources :branches do
    resources :people
    resources :contacts, only: :index
    member do
      get 'coordinator'
      get 'map'
      get 'awaiting_domestic_people'
      get 'domestic_members'
      get 'domestic_supporters'
      get 'guest_people'
      get 'unpaid_domestic_members'
    end
  end
  resources :organizations
  resources :people do
    resources :contacts
    resources :notes, only: [:new, :create]

    member do
      get 'application'
      get 'signed_application'
      get 'private'
      get 'photo'
      get 'cv'
      post 'approve'
      post 'reject'
      post 'cancel_membership'
      get 'cancel_membership_request'
    end
    collection do
      get 'profile'
      get 'dashboard'
      get 'beran_export'
    end
  end

  resources :supporter_memberships, only: [:new, :create]

  resources :regions do
    resources :people
    resources :branches, only: :index
    resources :councilors, only: :index
    resources :contacts, only: :index
    resource :body, only: :show
    member do
      get 'domestic_members'
      get 'domestic_supporters'
      get 'guest_people'
      get 'mestske_casti'
      get 'okresy'
      get 'map'
      get 'awaiting_domestic_people'
      get 'unpaid_domestic_members'
    end
  end

  resources :regions, path: "kraje"
  resources :councilors, path: "zastupitele"
  resources :councilors, only: :index

  post "/people/:id/supporter_payments", to: "finance_api#supporter_payments"
  post "/people/:id/member_payments", to: "finance_api#member_payments"
  get "/people/:id/payments", to: "finance_api#payments"
  post "/people/:id/supporter_paid", to: "finance_api#supporter_paid"
  post "/people/:id/member_paid", to: "finance_api#member_paid"

  root 'people#dashboard'
end

app/models/candidates_list.rb
class CandidatesList < ActiveRecord::Base

  # store :data, accessors: [ :params, :permitted_params, :changes, :previous_data ], coder: JSON
  serialize :kandidati #, coder: JSON

  def strana?
    typ_volebni_strany=="politická strana"
  end

  def ruian_data
    @ruian_data ||= HTTParty.get("http://openapi.cz/api/adresy/hledej/vse?dotaz=+kod_obce:#{kod_zastupitelstva}")["adresy"].
      first.symbolize_keys.extract!(:kod_obce, :nazev_obce, :kod_pou, :nazev_pou, :kod_orp, :nazev_orp, :kod_momc, :nazev_momc, :kod_mop, :nazev_mop, :kod_kraje, :nazev_kraje)
  end

  def ruian
    RuianAddress.new(
      mestska_cast:     ruian_data[:nazev_momc],
      mestska_cast_id:  ruian_data[:kod_momc],
      okres:            ruian_data[:nazev_okresu],
      okres_id:         ruian_data[:kod_okresu],
      obec:             ruian_data[:nazev_obce],
      obec_id:          ruian_data[:kod_obce],
      kraj:             ruian_data[:nazev_kraje],
      kraj_id:          ruian_data[:kod_kraje],
      orp:              ruian_data[:nazev_orp],
      orp_id:           ruian_data[:kod_orp]
    )
  end

  def branch
    @branch ||= BranchLocator.new(ruian).branch
  end

  def self.load_from_xlsx(candidates_list_file)
    workbook = RubyXL::Parser.parse(candidates_list_file.sheet.path)
    puts workbook.sheets.last.name
    kandidati = workbook["Kandidátní listina"].reject{ |row| row.nil? || row[0].nil? ||row[0].value.blank? }.select{ |row|
      puts row[0].value
      row[0].value.match(/\A(\d+\.|n.hradn.*)\z/)}.collect{ |row|
        begin
        {
          poradi: row[0].value.to_i==0 ? "náhr" : row[0].value.to_i,
          titul_pred: row[1].try(:value),
          jmeno: row[2].value,
          prijmeni: row[3].value,
          titul_za: row[4].try(:value),
          datum_narozeni: row[5].value.try(:to_date),
          pohlavi: row[6].value,
          povolani: row[7].value,
          obec: row[8].value,
          clenstvi_ve_strane: row[9].try(:value),
          adresa_bydliste: row[10].try(:value),
          navrhujici_strana: row[11].try(:value)
        }
        rescue
        {
          prijmeni: "Chyba importu",
          datum_narozeni: "2345-01-01"
        }
        end
      }.reject{|row| row[:prijmeni].nil?}

    self.new({
      candidates_list_file_id: candidates_list_file.id,
      druh_zastupitelstva: workbook["Hlavička"][5][1].value,
      kod_zastupitelstva: workbook["Hlavička"][6][1].value,
      nazev_zastupitelstva: workbook["Hlavička"][7][1].value,
      volebni_obvod: workbook["Hlavička"][8][1].try(:value),
      nazev_volebni_strany: workbook["Hlavička"][10][1].value,
      typ_volebni_strany: workbook["Hlavička"][11][1].value,
      nazev_strany_a_hnuti: workbook["Hlavička"][12][1].value,
      pocet_clenu_zastupitelstva: workbook["Hlavička"][14][1].value,
      zmocnenec_jmeno: workbook["Hlavička"][16][2].try(:value),
      zmocnenec_adresa: workbook["Hlavička"][17][2].try(:value),
      nahradnik_jmeno: workbook["Hlavička"][18][2].try(:value),
      nahradnik_adresa: workbook["Hlavička"][19][2].try(:value),
      kandidati: kandidati
      # kandidati: kandidati.collect{|kandidat| OpenStruct.new(kandidat)}
    })
  end
end

app/controllers/candidates_lists_controller.rb
class CandidatesListsController < ApplicationController

  def index
  end

  def new
    authorize!(:upload, CandidatesList)
    @candidates_list = CandidatesListFile.new
  end

  def preview
    authorize!(:upload, CandidatesList)
    candidates_list_file = CandidatesListFile.create(params.require(:candidates_list_file).permit(:sheet))
    @candidates_list = CandidatesList.load_from_xlsx(candidates_list_file)
  end

  def index
    authorize!(:read, CandidatesList)
    @candidates_lists = CandidatesList.all
  end

  def show
    authorize!(:read, CandidatesList)
    @candidates_list = CandidatesList.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = CandidatesListPdf.new(@candidates_list, params[:datum])
        send_data pdf.render,
                  filename: "kandidatni_listina.pdf",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
    end
  end

  def declaration
    authorize!(:generate_declaration, CandidatesList)
    candidates_list = CandidatesList.find(params[:candidates_list_id])
    candidate = candidates_list.kandidati[params[:id].to_i]
    respond_to do |format|
      format.html
      format.pdf do
        pdf = DeclarationPdf.new(candidate, candidates_list)
        send_data pdf.render,
                  filename: "prohlaseni_kandidata.pdf",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
    end
  end

  def declarations
    authorize!(:generate_declaration, CandidatesList)
    candidates_list = CandidatesList.find(params[:id])
    respond_to do |format|
      format.html
      format.zip do
        compressed_filestream = Zip::OutputStream.write_buffer do |zos|
          candidates_list["kandidati"].each_with_index do |candidate, index|
            zos.put_next_entry "prohlaseni-#{candidates_list['kod_zastupitelstva']}-#{index+1}.pdf"
            zos.print DeclarationPdf.new(candidate, candidates_list).render
          end
        end
        compressed_filestream.rewind
        send_data compressed_filestream.read, filename: "prohlaseni-#{candidates_list["kod_zastupitelstva"]}.zip"
      end
    end
  end

  def create
    authorize!(:upload, CandidatesList)
    respond_to do |format|
      Event.create(default_event_params.merge({
        command: "SaveCandidatesList",
        name: "CandidatesListSaved",
        params: JSON.load(Base64.decode64(params[:candidates_list]))
        # aggregate_type: "CandidatesList",
        # aggregate_id: SecureRandom.uuid
      }))
      format.html { redirect_to :new_candidates_list, notice: 'Kandidátní listina byla úspěšně uložena.' }
    end
  end

  def edit
    authorize!(:upload, CandidatesList)
    @candidates_list = CandidatesList.find(params[:id])
  end

  def update
    authorize!(:upload, CandidatesList)
    @candidates_list = CandidatesList.find(params[:id])
    respond_to do |format|
      if @candidates_list.update(params.require(:candidates_list).permit(:poznamka))
        format.html { redirect_to candidates_lists_path, notice: 'Poznámka uložena.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    def authorize_backoffice
      authorize!(:backoffice, :all)
    end
end

app/helpers/candidates_lists_helper.rb
module CandidatesListsHelper
  def genitivize(druh_zastupitelstva)
    case druh_zastupitelstva
    when /Zastupitelstvo (.*)/
      "zastupitelstva #{Regexp.last_match[1]}"
    else
      druh_zastupitelstva
    end
  end

  def cele_jmeno(kandidat)
    jmeno=kandidat[:titul_pred].blank? ? '' : "#{kandidat[:titul_pred]} "
    jmeno+=[kandidat[:jmeno], kandidat[:prijmeni]].join(' ')
    jmeno+=kandidat[:titul_za].blank? ? '' : ", #{kandidat[:titul_za]}"
  end

  def vek(kandidat, today=nil)
    now = today ? today.to_date : Date.today
    dob = kandidat[:datum_narozeni].to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end
end

app/views/candidates_lists/_sidebar.html.erb
<% content_for 'sidebar' do %>
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand" style="line-height: 20px; height: 30px"><%=link_to "Kandidátní listiny", candidates_lists_path %></li>
    <% for candidates_list in CandidatesList.all.order(:nazev_zastupitelstva) %>
    <li style="line-height: 20px"><%= link_to_unless_current candidates_list[:nazev_zastupitelstva], candidates_list %></a></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/candidates_lists/edit.html.erb
<% render 'backoffice/sidebar' %>
<% page_title "Kandidátní listina #{@candidates_list.nazev_zastupitelstva}" %>
<%= simple_form_for @candidates_list do |f| %>
<%= f.input :poznamka, label: "Poznámka" %>
<%= f.button :submit, value: "Uložit", class: 'btn btn-success' %>
<% end %>

app/views/candidates_lists/index.html.erb
<%
  page_title 'Seznam kandidátních listin'
  render 'sidebar'
%>


<%= link_to("Nahrát novou", new_candidates_list_path, class: "btn btn-primary pull-right") if can?(:upload, CandidatesList)%>

<table class="table">
  <thead>
    <tr>
      <th>Název zastupitelstva</th><th>Počet míst</th><th>Počet kandidátů</th><th>Poznámka</th>
    </tr>
  </thead>
  <tbody>
    <% @candidates_lists.each do |candidates_list| %>
    <tr>
      <td><%= candidates_list.nazev_zastupitelstva %></td>
      <td><%= candidates_list.pocet_clenu_zastupitelstva %></td>
      <td><%= candidates_list.kandidati.size %></td>
      <td><%= candidates_list.poznamka %></td>
      <td><%= link_to("Detail", candidates_list) if can?(:read, CandidatesList)%> <%=link_to("Upravit", edit_candidates_list_path(candidates_list)) if can?(:upload, CandidatesList)%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/candidates_lists/new.html.erb
<%
  page_title 'Nová kandidátní listina nebo nová verze'
  render 'backoffice/sidebar'
%>

<p>Zde prosím nahrajte novou nebo aktualizovanou kandidátní listinu. Před uložením bude zpracována a zobrazena ke kontrole.</p>

<%= simple_form_for(@candidates_list, url: preview_candidates_lists_path) do |f| %>
  <%= f.input :sheet, label: "Kandidátní listina" %>
  <%= f.button :submit, "Načíst kandidátní listinu" %>
<% end %>

app/views/candidates_lists/preview.html.erb
<%
  page_title 'Kontrola načtení kandidátní listiny'
  render 'backoffice/sidebar'
%>

<p>Zkontrolujte, prosím, zda jsou pole načtena správně. Pokud ne, nahrajte znovu upravený soubor, jinak kandidátní listinu uložte.</p>

<table class="table table-condensed">
  <tbody>
    <tr><th>Druh zastupitelstva</th><td><%= @candidates_list['druh_zastupitelstva'] %></td></tr>
    <tr><th>Kód zastupitelstva</th><td><%= @candidates_list.kod_zastupitelstva %></td></tr>
    <tr><th>Název zastupitelstva</th><td><%= @candidates_list.nazev_zastupitelstva %></td></tr>
    <tr><th>Volební obvod</th><td><%= @candidates_list.volebni_obvod %></td></tr>
    <tr><th>Název volební strany</th><td><%= @candidates_list.nazev_volebni_strany %></td></tr>
    <tr><th>Typ volební strany</th><td><%= @candidates_list.typ_volebni_strany %></td></tr>
    <tr><th>Název strany a hnutí</th><td><%= @candidates_list.nazev_strany_a_hnuti %></td></tr>
    <tr><th>Počet členů zastupitelstva</th><td><%= @candidates_list.pocet_clenu_zastupitelstva %></td></tr>
    <tr><th>Jméno zmocněnce</th><td><%= @candidates_list.zmocnenec_jmeno %></td></tr>
    <tr><th>Addresa zmocněnce</th><td><%= @candidates_list.zmocnenec_adresa %></td></tr>
    <tr><th>Jméno náhradníka</th><td><%= @candidates_list.nahradnik_jmeno %></td></tr>
    <tr><th>Addresa náhradníka</th><td><%= @candidates_list.nahradnik_adresa %></td></tr>
  </tbody>
</table>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Pořadí</th>
      <th>Titul</th>
      <th>Jméno</th>
      <th>Příjmení</th>
      <th>Titul</th>
      <th>Datum narození</th>
      <th>Pohlaví</th>
      <th>Povolání</th>
      <th>Obec/část</th>
      <th>Členství ve straně</th>
      <th>Adresa bydliště</th>
    </tr>
  </thead>
  <tbody>
    <% @candidates_list.kandidati.each do |candidate| %>
    <tr>
      <td><%= candidate[:poradi] %>.</td>
      <td><%= candidate[:titul_pred] %></td>
      <td><%= candidate[:jmeno] %></td>
      <td><%= candidate[:prijmeni] %></td>
      <td><%= candidate[:titul_za] %></td>
      <td><%= candidate[:datum_narozeni].to_date %></td>
      <td><%= candidate[:pohlavi] %></td>
      <td><%= candidate[:povolani] %></td>
      <td><%= candidate[:obec] %></td>
      <td><%= candidate[:clenstvi_ve_strane] %></td>
      <td><%= candidate[:adresa_bydliste] %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= button_to "Uložit kandidátní listinu", candidates_lists_path, method: :post, params: {candidates_list: Base64.encode64(@candidates_list.to_json)}%>

app/views/candidates_lists/show.html.erb
<%
  page_title 'Kandidátní listina'
  render 'sidebar'
%>

<table class="table table-condensed">
  <tbody>
    <tr><th>Druh zastupitelstva</th><td><%= @candidates_list['druh_zastupitelstva'] %></td></tr>
    <tr><th>Kód zastupitelstva</th><td><%= @candidates_list.kod_zastupitelstva %></td></tr>
    <tr><th>Název zastupitelstva</th><td><%= @candidates_list.nazev_zastupitelstva %></td></tr>
    <tr><th>Volební obvod</th><td><%= @candidates_list.volebni_obvod %></td></tr>
    <tr><th>Název volební strany</th><td><%= @candidates_list.nazev_volebni_strany %></td></tr>
    <tr><th>Typ volební strany</th><td><%= @candidates_list.typ_volebni_strany %></td></tr>
    <tr><th>Název strany a hnutí</th><td><%= @candidates_list.nazev_strany_a_hnuti %></td></tr>
    <tr><th>Počet členů zastupitelstva</th><td><%= @candidates_list.pocet_clenu_zastupitelstva %></td></tr>
    <tr><th>Jméno zmocněnce</th><td><%= @candidates_list.zmocnenec_jmeno %></td></tr>
    <tr><th>Addresa zmocněnce</th><td><%= @candidates_list.zmocnenec_adresa %></td></tr>
    <tr><th>Jméno náhradníka</th><td><%= @candidates_list.nahradnik_jmeno %></td></tr>
    <tr><th>Addresa náhradníka</th><td><%= @candidates_list.nahradnik_adresa %></td></tr>
    <tr><th></th><td><%= link_to("PDF", candidates_list_path(@candidates_list,format: 'pdf'), class: "btn btn-default") %></td></tr>
    <tr><th>Poznámka</th><td><%= @candidates_list.poznamka %></td></tr>
  </tbody>
</table>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Pořadí</th>
      <th>Titul</th>
      <th>Jméno</th>
      <th>Příjmení</th>
      <th>Titul</th>
      <th>Datum narození</th>
      <th>Pohlaví</th>
      <th>Povolání</th>
      <th>Obec/část</th>
      <th>Členství ve straně</th>
      <th>Adresa bydliště</th>
      <% unless @candidates_list.strana? %>
      <th>Navrhující strana</th>
      <% end %>
      <th><%= link_to("Všechna prohlášení", declarations_path(params[:id],format: 'zip'), class: "btn btn-primary btn-xs") %></th>
    </tr>
  </thead>
  <tbody>
    <% @candidates_list.kandidati.each_with_index do |candidate, index| %>
    <tr>
      <td><%= candidate[:poradi] %>.</td>
      <td><%= candidate[:titul_pred] %></td>
      <td><%= candidate[:jmeno] %></td>
      <td><%= candidate[:prijmeni] %></td>
      <td><%= candidate[:titul_za] %></td>
      <td><%= candidate[:datum_narozeni].to_date %></td>
      <td><%= candidate[:pohlavi] %></td>
      <td><%= candidate[:povolani] %></td>
      <td><%= candidate[:obec] %></td>
      <td><%= candidate[:clenstvi_ve_strane] %></td>
      <td><%= candidate[:adresa_bydliste] %></td>
      <% unless @candidates_list.strana? %>
      <td><%= candidate[:navrhujici_strana] %></td>
      <% end %>
      <td><%= link_to("Prohlášení", declaration_path(params[:id],index,format: 'pdf')) if can?(:generate_declaration, CandidatesList)%></td>
    </tr>
    <% end %>
  </tbody>
</table>